openapi: 3.0.0
info:
  title: Analytics Service API
  version: 1.0.0
  description: API documentation for the Analytics Service
servers:
  - url: /api/v1
paths:
  /analytics:
    get:
      summary: Get all analytics
      tags:
        - Analytics
      responses:
        '200':
          description: A list of analytics
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Analytics fetched successfully
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAnalytic'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
    post:
      summary: Create a new analytic
      tags:
        - Analytics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAnalytic'
      responses:
        '201':
          description: The created analytic
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Analytic created successfully
                  data:
                    $ref: '#/components/schemas/UserAnalytic'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
  /analytics/{id}:
    get:
      summary: Get an analytic by ID
      tags:
        - Analytics
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the analytic to fetch
          schema:
            type: string
      responses:
        '200':
          description: The requested analytic
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Analytic fetched successfully
                  data:
                    $ref: '#/components/schemas/UserAnalytic'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
        '404':
          description: Analytic not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Analytic not found
                  appCode:
                    type: string
                    example: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
    post:
      summary: Get or create an analytic by ID
      tags:
        - Analytics
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the analytic
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAnalytic'
      responses:
        '200':
          description: The analytic (fetched or newly created)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Analytic fetched or created successfully
                  data:
                    $ref: '#/components/schemas/UserAnalytic'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
  /analytics/user/{userId}:
    get:
      summary: Get analytics by user ID
      tags:
        - Analytics
      parameters:
        - in: path
          name: userId
          required: true
          description: ID of the user whose analytics to fetch
          schema:
            type: string
      responses:
        '200':
          description: Analytics for the specified user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Analytics fetched successfully
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAnalytic'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
        '404':
          description: No analytics found for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: No analytics found for the user
                  appCode:
                    type: string
                    example: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
components:
  schemas:
    UserAnalytic:
      type: object
      properties:
        _id:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6f9e'
        userId:
          type: string
          example: 'user123'
        userItineraryAnalytic:
          type: object
          properties:
            totalCommentsCount:
              type: integer
              example: 10
            avgComments:
              type: number
              example: 2.5
        userPublicationAnalytic:
          type: object
          properties:
            totalCommentsCount:
              type: integer
              example: 15
            averageLike:
              type: number
              example: 4.5
        analysisDate:
          type: string
          format: date-time
          example: '2023-12-01T12:00:00.000Z'
    NewAnalytic:
      type: object
      properties:
        userId:
          type: string
          example: 'user123'
        userItineraryAnalytic:
          type: object
          properties:
            totalCommentsCount:
              type: integer
              example: 10
            avgComments:
              type: number
              example: 2.5
        userPublicationAnalytic:
          type: object
          properties:
            totalCommentsCount:
              type: integer
              example: 15
            averageLike:
              type: number
              example: 4.5
